# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: .packit_rpm/elfutils.spec

synced_files:
    - .packit.yaml
    - src: .packit_rpm/elfutils.spec
      dest: elfutils.spec

upstream_package_name: elfutils
downstream_package_name: elfutils
upstream_project_url: https://sourceware.org/elfutils/
upstream_tag_template: "elfutils-{version}"


actions:
  post-upstream-clone:
    # Use the Fedora Rawhide specfile
    - "git clone https://src.fedoraproject.org/rpms/elfutils .packit_rpm --depth=1"
    # Drop the "sources" file so rebase-helper doesn't think we're a dist-git
    - "rm -fv .packit_rpm/sources"
    # Drop patches
    - "sed -ri '/^Patch[0-9][0-9]?:.+\\.patch/d' .packit_rpm/elfutils.spec"
    - sed -i '/configure CFLAGS=/s/$/ --enable-maintainer-mode/' .packit_rpm/elfutils.spec

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-35-aarch64
    - fedora-35-armhfp
    - fedora-35-i386
    - fedora-35-ppc64le
    - fedora-35-s390x
    - fedora-35-x86_64
    - fedora-rawhide-x86_64
