name: Coverity

on:
  schedule:
    # send data to Coverity daily at midnight
    - cron:  '0 0 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: github.repository == 'evverx/elfutils'
    env:
      COVERITY_SCAN_TOKEN: "${{ secrets.COVERITY_SCAN_TOKEN }}"
      COVERITY_SCAN_EMAIL: "${{ secrets.COVERITY_SCAN_EMAIL }}"
    steps:
      - name: Repository checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Ubuntu setup
        run: sudo -E .github/workflows/unit_tests.sh SETUP
      - name: Coverity
        run: .github/workflows/unit_tests.sh COVERITY
